enum WebSocketOpCodeServer {
  WSS_TO_API__2FA_VALIDATION__RESPONSE = "WSS_TO_API__2FA_VALIDATION__RESPONSE",
  WSS_FROM_PLUGIN__2FA_VALIDATION__REQUEST = "WSS_FROM_PLUGIN__2FA_VALIDATION__REQUEST",
  WSS_FROM_API__2FA_VALIDATION__RESPONSE = "WSS_FROM_API__2FA_VALIDATION__RESPONSE",

  WSS_FROM_PLUGIN__UPDATE_ACCOUNT_STATE__REQUEST = "WSS_FROM_PLUGIN__UPDATE_ACCOUNT_STATE__REQUEST",
  WSS_TO_API__UPDATE_ACCOUNT_STATE__RESPONSE = "WSS_TO_API__UPDATE_ACCOUNT_STATE__RESPONSE",

  WSS_FROM_API__ACCOUNT_BLOCK__REQUEST = "WSS_FROM_API__ACCOUNT_BLOCK__REQUEST",
  WSS_TO_PLUGIN__ACCOUNT_BLOCK__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_BLOCK__RESPONSE",

  WSS_FROM_API__ACCOUNT_SET_TO_CONFIG__REQUEST = "WSS_FROM_API__ACCOUNT_SET_TO_CONFIG__REQUEST",
  WSS_TO_PLUGIN__ACCOUNT_SET_TO_CONFIG__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_SET_TO_CONFIG__RESPONSE",

  // Demande de création du compte
  WSS_FROM_PLUGIN__ACCOUNT_ACTIVATION__REQUEST = "WSS_FROM_PLUGIN__ACCOUNT_ACTIVATION__REQUEST",
  WSS_TO_API__ACCOUNT_ACTIVATION__RESPONSE = "WSS_TO_API__ACCOUNT_ACTIVATION__RESPONSE",

  // Ajout dans enabled
  WSS_FROM_API__ACCOUNT_ACTIVATION__REQUEST = "WSS_FROM_API__ACCOUNT_ACTIVATION__REQUEST",
  WSS_TO_PLUGIN__ACCOUNT_ACTIVATION__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_ACTIVATION__RESPONSE",

  WSS_FROM_API__ACCOUNT_VERIFY_PASSWORD__REQUEST = "WSS_FROM_API__ACCOUNT_VERIFY_PASSWORD__REQUEST",
  WSS_TO_PLUGIN__ACCOUNT_VERIFY_PASSWORD__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_VERIFY_PASSWORD__RESPONSE",

  WSS_FROM_API__FORCE_TS_ACCOUNT_DISCONNECTION__REQUEST = "WSS_FROM_API__FORCE_TS_ACCOUNT_DISCONNECTION__REQUEST",
  WSS_TO_PLUGIN__FORCE_TS_ACCOUNT_DISCONNECTION__RESPONSE = "WSS_TO_PLUGIN__FORCE_TS_ACCOUNT_DISCONNECTION__RESPONSE",

  WSS_FROM_API__CHECK_TS_ACCOUNT_CONNECTION_STATE__REQUEST = "WSS_FROM_API__CHECK_TS_ACCOUNT_CONNECTION_STATE__REQUEST",
  WSS_TO_PLUGIN__CHECK_TS_ACCOUNT_CONNECTION_STATE__RESPONSE = "WSS_TO_PLUGIN__CHECK_TS_ACCOUNT_CONNECTION_STATE__RESPONSE",

  WSS_FROM_PLUGIN__GET_STATS_WORKSPACE_OR_ADD__REQUEST = "WSS_FROM_PLUGIN__GET_STATS_WORKSPACE_OR_ADD__REQUEST",
  WSS_TO_API__GET_STATS_WORKSPACE_OR_ADD__RESPONSE = "WSS_TO_API__GET_STATS_WORKSPACE_OR_ADD__RESPONSE",

  WSS_FROM_API__VERIFY_ACCESS_NUMERIC_PASSWORD__REQUEST = "WSS_FROM_API__VERIFY_ACCESS_NUMERIC_PASSWORD__REQUEST",
  WSS_TO_PLUGIN__VERIFY_ACCESS_NUMERIC_PASSWORD__RESPONSE = "WSS_TO_PLUGIN__VERIFY_ACCESS_NUMERIC_PASSWORD__RESPONSE",

  WSS_FROM_API__ADD_NUMERIC_PASSWORD_GROUP__REQUEST = "WSS_FROM_API__ADD_NUMERIC_PASSWORD_GROUP__REQUEST",
  WSS_TO_PLUGIN__ADD_NUMERIC_PASSWORD_GROUP__RESPONSE = "WSS_TO_PLUGIN__ADD_NUMERIC_PASSWORD_GROUP__RESPONSE",

  WSS_FROM_PLUGIN__SEND_SMS_CODE__REQUEST = "WSS_FROM_PLUGIN__SEND_SMS_CODE__REQUEST",
  WSS_TO_API__SEND_SMS_CODE__RESPONSE = "WSS_TO_API__ACCOUNT_ACTIVATION__RESPONSE",

  WSS_TO_API__HAS_NOTIFICATION_VALIDATION__RESPONSE = "WSS_TO_API__HAS_NOTIFICATION_VALIDATION__RESPONSE",
  WSS_TO_API__TWO_FA_VALIDATION__RESPONSE = "WSS_TO_API__TWO_FA_VALIDATION__RESPONSE",
  WSS_TO_API__GENERATE_TOKEN_ACCESS__RESPONSE = "WSS_TO_API__GENERATE_TOKEN_ACCESS__RESPONSE",

  WSS_TO_API__VERIFY_AUTH_TOKEN__RESPONSE = "WSS_TO_API__VERIFY_AUTH_TOKEN__RESPONSE",
  WSS_TO_API__HAS_ACCESS_TO_AUTHENTICATION__RESPONSE = "WSS_TO_API__HAS_ACCESS_TO_AUTHENTICATION__RESPONSE",
  WSS_TO_API__GENERATE_ACTIVATION_CODE__RESPONSE = "WSS_TO_API__GENERATE_ACTIVATION_CODE__RESPONSE",
  WSS_TO_API__GET_ALL_SERVICE__RESPONSE = "WSS_TO_API__GET_ALL_SERVICE__RESPONSE",

  // WSS_FROM_API__VALIDATE_NEW_DEVICE_ASK__REQUEST = "WSS_FROM_API__VALIDATE_NEW_DEVICE_ASK__REQUEST",
  // WSS_TO_PLUGIN__VALIDATE_NEW_DEVICE_ASK__RESPONSE = "WSS_TO_PLUGIN__VALIDATE_NEW_DEVICE_ASK__RESPONSE",
  //
  // WSS_FROM_API__ACCOUNT_NEXT_LOGIN_CONTROL_PWD__REQUEST = "WSS_FROM_API__ACCOUNT_NEXT_LOGIN_CONTROL_PWD__REQUEST",
  // WSS_TO_PLUGIN__ACCOUNT_NEXT_LOGIN_CONTROL_PWD__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_NEXT_LOGIN_CONTROL_PWD__RESPONSE",
  //
  // WSS_FROM_API__ACCOUNT_NEXT_LOGIN_CONTROL_PWD_WITH_2FA__REQUEST = "WSS_FROM_API__ACCOUNT_NEXT_LOGIN_CONTROL_PWD_WITH_2FA__REQUEST",
  // WSS_TO_PLUGIN__ACCOUNT_NEXT_LOGIN_CONTROL_PWD_WITH_2FA__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_NEXT_LOGIN_CONTROL_PWD_WITH_2FA__RESPONSE",
  //
  // WSS_FROM_API__ACCOUNT_INFORMATIONS__REQUEST = "WSS_FROM_API__ACCOUNT_INFORMATIONS__REQUEST",
  // WSS_TO_PLUGIN__ACCOUNT_INFORMATIONS__RESPONSE = "WSS_TO_PLUGIN__ACCOUNT_INFORMATIONS__RESPONSE",

  // WSS_FROM_PLUGIN__MOBILE_MESSAGE__REQUEST = "WSS_FROM_PLUGIN__MOBILE_MESSAGE__REQUEST",
  // WSS_TO_API__MOBILE_MESSAGE__RESPONSE = "WSS_TO_API__MOBILE_MESSAGE__RESPONSE",

  // WSS_FROM_PLUGIN__SERVICE_PASSWORD_HAS_BEEN_VALIDATED__REQUEST = "WSS_FROM_PLUGIN__SERVICE_PASSWORD_HAS_BEEN_VALIDATED__REQUEST",
  // WSS_TO_API__SERVICE_PASSWORD_HAS_BEEN_VALIDATED__RESPONSE = "WSS_TO_API__SERVICE_PASSWORD_HAS_BEEN_VALIDATED__RESPONSE",
  //
  // WSS_FROM_PLUGIN__SERVICE_PASSWORD_WITH_2FA_HAS_BEEN_VALIDATED__REQUEST = "WSS_FROM_PLUGIN__SERVICE_PASSWORD_WITH_2FA_HAS_BEEN_VALIDATED__REQUEST",
  // WSS_TO_API__SERVICE_PASSWORD_WITH_2FA_HAS_BEEN_VALIDATED__RESPONSE = "WSS_TO_API__SERVICE_PASSWORD_WITH_2FA_HAS_BEEN_VALIDATED__RESPONSE",
  //
  // WSS_FROM_API__ACCOUNT_VALIDATE_API_RESET_PASSWORD__REQUEST = "WSS_FROM_API__ACCOUNT_VALIDATE_API_RESET_PASSWORD__REQUEST",
  // WSS_FROM_PLUGIN__ACCOUNT_VALIDATE_API_RESET_PASSWORD__RESPONSE = "WSS_FROM_PLUGIN__ACCOUNT_VALIDATE_API_RESET_PASSWORD__RESPONSE",
  //
  // WSS_FROM_PLUGIN__SERVICE_VALIDATE_ADD_DEVICE__REQUEST = "WSS_FROM_PLUGIN__SERVICE_VALIDATE_ADD_DEVICE__REQUEST",
  // WSS_TO_API__SERVICE_VALIDATE_ADD_DEVICE__RESPONSE = "WSS_TO_API__SERVICE_VALIDATE_ADD_DEVICE__RESPONSE",
  //
  // WSS_FROM_API__VALIDATE_REMOVE_DEVICE_ASK__REQUEST = "WSS_FROM_API__VALIDATE_REMOVE_DEVICE_ASK__REQUEST",
  // WSS_TO_PLUGIN__VALIDATE_REMOVE_DEVICE_ASK__RESPONSE = "WSS_TO_PLUGIN__VALIDATE_REMOVE_DEVICE_ASK__RESPONSE",
  //
  // WSS_FROM_PLUGIN__SERVICE_VALIDATE_REMOVE_DEVICE__REQUEST = "WSS_FROM_PLUGIN__SERVICE_VALIDATE_REMOVE_DEVICE__REQUEST",
  // WSS_TO_API__SERVICE_VALIDATE_REMOVE_DEVICE__RESPONSE = "WSS_TO_API__SERVICE_VALIDATE_REMOVE_DEVICE__RESPONSE",

  // WSS_FROM_API__VALIDATE_REMOVE_WORKSPACE_ASK__REQUEST = "WSS_FROM_API__VALIDATE_REMOVE_WORKSPACE_ASK__REQUEST",
  // WSS_TO_PLUGIN__VALIDATE_REMOVE_WORKSPACE_ASK__RESPONSE = "WSS_TO_PLUGIN__VALIDATE_REMOVE_WORKSPACE_ASK__RESPONSE",
  //
  // WSS_FROM_PLUGIN__CONFIRMATION_REMOVE_WORKSPACE__REQUEST = "WSS_FROM_PLUGIN__CONFIRMATION_REMOVE_WORKSPACE__REQUEST",
  // WSS_TO_API__CONFIRMATION_REMOVE_WORKSPACE__RESPONSE = "WSS_TO_API__CONFIRMATION_REMOVE_WORKSPACE__RESPONSE",

  WSS_FROM_ANY__WS_DISCONNECTION__RESPONSE = "WSS_FROM_ANY__WS_DISCONNECTION__RESPONSE",
  WSS_FROM_ANY__WS_CONNECTION__REQUEST = "WSS_FROM_ANY__WS_CONNECTION__REQUEST",
  WSS_FROM_ANY__INVALID__REQUEST = "WSS_FROM_ANY__INVALID__REQUEST",
  WSS_FROM_ANY__ERROR_HAS_OCCURRED__RESPONSE = "WSS_FROM_ANY__ERROR_HAS_OCCURRED__RESPONSE",
  WSS_FROM_ANY__INVALID_SIGNATURE__REQUEST = "WSS_FROM_ANY__INVALID_SIGNATURE__REQUEST",
  WSS_TO_API__MOBILE_MESSAGE__RESPONSE = "WSS_TO_API__MOBILE_MESSAGE__RESPONSE"
}

export default WebSocketOpCodeServer;
